### ISSUE TITLE
...

### ISSUE THREAD

**Issue by romanman** [merito/kwatermistrz3000#1]

**Comment by romanman** [comment]
@merito: can you comment here please?

**Comment by merito** [comment]
Sorry, but there is no way to sell my account. Bye

**Comment by romanman** [comment]
Not even for 1000 usd?

**Comment by romanman** [comment]
...

**Comment by merito** [comment]
As you can find [here](https://help.github.com/articles/name-squatting-policy/])

> Attempts to sell, buy, or solicit other forms of payment in exchange for account names are prohibited and may result in permanent account suspension.

**Comment by romanman** [comment]
.
